name: Deploy to Server

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Synchronize files to the server
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          TARGET_USER: ${{ secrets.DEPLOY_USER }}
          TARGET_SERVER: ${{ secrets.DEPLOY_SERVER }}
          TARGET_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$TARGET_SERVER" >> ~/.ssh/known_hosts

          # Define taget and temp dir
          TEMP_PATH="~/deploy.tmp"
          FINAL_PATH="$TARGET_PATH"

          # sync files to remote
          rsync -avz --delete --filter=':- .deployignore' . "$TARGET_USER@$TARGET_SERVER:$TEMP_PATH"

          # Switch current release with previous
          ssh $TARGET_USER@$TARGET_SERVER "
            rm -rf ~/deploy.bak;
            mv $FINAL_PATH ~/deploy.bak || true;
            mv $TEMP_PATH $FINAL_PATH;
          "
          
      # Post release info to discord
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "11342935"
          username: "Release Changelog"
          avatar_url: "https://raw.githubusercontent.com/Brocky/gakuscan/refs/heads/main/assets/logo.png"
          footer_title: "Changelog"
          footer_icon_url: "https://raw.githubusercontent.com/Brocky/gakuscan/refs/heads/main/assets/logo.png"
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: false
